apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.config.jwtExpireMinutes | quote }}
