sonar.projectKey=informtoankit_Social-Media-app-devops
sonar.organization=informtoankit
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc
